version: '3.7'

services:

  server:
    container_name: simple_vue_app_server_dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    #env_file:
    #  - ./env/dev/.env