version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: flask run
    volumes:
      - ./simple_flask_app:/app
    ports:
      - 5000:5000
    #env_file:
    #  - ./env/dev/.env